image: Ubuntu2004
build: "off"
environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor
init:
- sh: curl -sflL https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh | bash -e -
install:
- sudo apt-get update >/dev/null
- sudo apt-get -y install lxc debootstrap squashfs-tools awscli >/dev/null
- lxc image list
- lxc image list images: null
- sudo snap install distrobuilder --classic >/dev/null
- lxd init --auto
- lxd init --dump
- |
  REL=$(curl -sI https://cdn.amazonlinux.com/os-images/latest/ | sed -En 's/location:.*os-images\/([^\/]+)\/.*/\1/p')
    && echo $REL
    && sudo distrobuilder build-lxd amazonlinux.yaml -o image.release=$REL
- lxc image import lxd.tar.xz rootfs.squashfs --alias my-local-image
- lxc image list
- time lxc launch my-local-image my-container
- lxc exec my-container -- timeout 2m bash -c 'echo waiting for newtork; until ping -c 1 google.com &>/dev/null; do sleep 1; done'
- lxc list
