image: Ubuntu2004
build: "off"
environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor
init:
- sh: curl -sflL https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh | bash -e -
install:
- sudo apt-get update >/dev/null
- sudo snap install distrobuilder --classic >/dev/null
- sudo apt-get -y install lxc debootstrap squashfs-tools awscli >/dev/null
- lxd init --auto
- lxd init --dump

- rm -f lxd.tar.xz rootfs.squashfs
- sudo distrobuilder build-lxd ubuntu.yaml -o image.architecture=amd64 -o image.release=focal
- lxc image import lxd.tar.xz rootfs.squashfs --alias local-ubuntu-image
- lxc image list
- rm -f lxd.tar.xz rootfs.squashfs

- rm -f lxd.tar.xz rootfs.squashfs
- curl -LO https://us.lxd.images.canonical.com/images/amazonlinux/current/amd64/default/20230205_05:09/lxd.tar.xz
- curl -LO https://us.lxd.images.canonical.com/images/amazonlinux/current/amd64/default/20230205_05:09/rootfs.squashfs
- lxc image import lxd.tar.xz rootfs.squashfs --alias local-amazon-image
- lxc image list
- rm -f lxd.tar.xz rootfs.squashfs

- rm -f lxd.tar.xz rootfs.squashfs
- |
    REL=$(curl -sI https://cdn.amazonlinux.com/os-images/latest/ | sed -En 's/location:.*os-images\/([^\/]+)\/.*/\1/p')
    echo $REL
    sudo distrobuilder build-lxd amazonlinux.yaml -o image.release=$REL
- lxc image import lxd.tar.xz rootfs.squashfs --alias local-amazon-image1
- lxc image list
- rm -f lxd.tar.xz rootfs.squashfs

- curl -LO https://us.lxd.images.canonical.com/images/amazonlinux/current/amd64/default/20230205_05:09/lxd.tar.xz
- curl -LO https://us.lxd.images.canonical.com/images/amazonlinux/current/amd64/default/20230205_05:09/rootfs.squashfs
- lxc image import lxd.tar.xz rootfs.squashfs --alias local-amazon-image2
- lxc image list
- rm -f lxd.tar.xz rootfs.squashfs

- time lxc launch local-ubuntu-image c-ubuntu
- lxc exec c-ubuntu -- timeout 2m bash -c 'echo waiting for newtork; until ping -c 1 google.com &>/dev/null; do sleep 1; done'
- lxc list

- time lxc launch local-amazon-image c-amazon
- lxc exec c-amazon -- timeout 2m bash -c 'echo waiting for newtork; until ping -c 1 google.com &>/dev/null; do sleep 1; done'
- lxc list
