image: Ubuntu2004
build: "off"
environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFp48yQviDu3U2mGdwv7CO3O84IAj4LJUXzyGbs6mT0q taylor
  matrix:
  - distro: amazonlinux
    distro_file: image-amazonlinux.yaml
    image_name: local-amazon-image
  - distro: ubuntu
    distro_file: image-ubuntu.yaml
    image_name: local-ubuntu-image
  - distro: alpine
    distro_file: image-alpine.yaml
    image_name: local-alpine-image
matrix:
  fast_finish: false
init:
- sh: curl -sflL https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh | bash -e -
install:
- sudo apt-get update >/dev/null
- sudo snap install distrobuilder --classic >/dev/null
- sudo apt-get -y install lxc debootstrap squashfs-tools awscli >/dev/null
- lxd init --auto
- lxd init --dump
- rm -f lxd.tar.xz rootfs.squashfs
- sudo distrobuilder build-lxd ${distro_file} -o image.architecture=amd64 -o image.release=focal
- lxc image import lxd.tar.xz rootfs.squashfs --alias ${image_name}
- lxc image list
