name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  lxc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable
    - name: Launch instance
      run: |
        sudo snap install distrobuilder
        distrobuilder --version
        curl -LO https://raw.githubusercontent.com/lxc/lxc-ci/master/images/amazonlinux.yaml
        sudo distrobuilder build-lxd amazonlinux.yaml -o image.release=2.0.20220606.1
