name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  lxc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable
    - name: Install distrobuilder
      run: |
        sudo snap install distrobuilder --classic
        sudo apt-get -y install lxc debootstrap squashfs-tools awscli >/dev/null
        distrobuilder --version
    - name: Flail aimlessly
      run: |
        sudo distrobuilder build-lxd ubuntu.yaml -o image.architecture=amd64 -o image.release=focal
        mkdir -p /tmp/s3/
        cp lxd.tar.xz rootfs.squashfs /tmp/s3/
        lxd init --auto
        lxc image import lxd.tar.xz rootfs.squashfs --alias local-image-sls
        lxc image list
        time lxc launch local-image-sls csls
        lxc exec csls -- bash -c 'echo waiting for newtork; until ping -c 1 google.com &>/dev/null; do sleep 1; done'
