name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  lxc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable
    - name: lxc init
      run: |
        lxd init --auto
    - name: Install distrobuilder
      run: |
        sudo snap install distrobuilder --classic
        distrobuilder --version
    - name: Import container
      run: |
        curl -LO https://raw.githubusercontent.com/lxc/lxc-ci/master/images/amazonlinux.yaml
        sudo distrobuilder build-lxd amazonlinux.yaml -o image.release=2.0.20220606.1
        du -shc lxd.tar.xz rootfs.squashfs
        lxc image import lxd.tar.xz rootfs.squashfs --alias amazon
        lxc image list
    - name: Launch container
      run: |
        lxc launch amazon c1
        lxc info
    - name: Test
      run: |
        lxc file push test.sh c1/tmp/
        ps aux | grep dnsmasq
        ip addr
        lxc exec c1 -- sudo bash -x /tmp/test.sh
