name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  lxc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stuff
      run: |
        pwd
    - uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable
    - name: Install distrobuilder
      run: |
        sudo snap install distrobuilder --classic
        distrobuilder --version
    - name: Import container
      run: |
        curl -LO https://raw.githubusercontent.com/lxc/lxc-ci/master/images/amazonlinux.yaml
        sudo distrobuilder build-lxd amazonlinux.yaml -o image.release=2.0.20220606.1
        du -shc lxd.tar.xz rootfs.squashfs
        lxc image import lxd.tar.xz rootfs.squashfs --alias amazon
        lxc image list
    - name: Launch lxc container
      run: |
        lxc launch amazon c1
    - name: Install stuff
      run: |
        lxc exec c1 -- sudo bash -x test.sh
